import React from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { dark, neobrutalism } from "@clerk/themes";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "NdiHub",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [dark],
      }}
    >
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1">{children}</main>
      </div>

      <SanityLive />
    </ClerkProvider>
  );
}
